name: build-and-test

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and Test
        run: |
          docker build -t int-test-course -f 6.\ Real\ world\ testing/tests/Customers.Api.Tests.Integration/Dockerfile .
          docker run -v /var/run/docker.sock.raw:/var/run/docker.sock --name int-test-container int-test-course

      - name: Cleanup
        if: always()
        run: docker rm int-test-container
